var a= prompt("Quelle est la valeur de a ?");
var b= prompt("Quelle est la valeur de b ?");
a=parseFloat(a);
b=parseFloat(b);
var resultat= a*b;
var resultatcarrée=a*a;
var resultatcarrée2=b*b;
var resultat2=a/b;
var resultat3=a+b;
var resultat4=a-b;
var resultat5=b-a;
var resultat6=b/a;
var resultat7=a%b;
var resultat8=b%a;
var resultat9=a*(a+b);
var resultat10=b*(a+b);
var resultat11=(a+b)*(a+b);
var resultat12=(a+b)*(b+a);
var resultat13=(b+a)*(b+a);
var resultat14=(b+a)/(a+b);
confirm("le produit de a*b est égal à : "+resultat);
confirm("le produit de a/b est égal à : "+resultat2);
confirm("le produit de a+b est égal à : "+resultat3);
confirm("le produit de a-b est égal à : "+resultat4);
confirm("le produit de b-a est égal à : "+resultat5);
confirm("le produit de b/a est égal à : "+resultat6);
confirm("le produit de a%b est égal à : "+resultat7);
confirm("le produit de b%a est égal à : "+resultat8);
confirm("le produit de a*a est égal à : "+resultatcarrée);
confirm("le produit de b*b est égal à : "+resultatcarrée2);
confirm("le produit de a(a+b) est égal à : "+resultat9);
confirm("le produit de b(a+b) est égal à : "+resultat10);
confirm("le produit de (a+b)(a+b) est égal à : "+resultat11);
confirm("le produit de (a+b)(b+a) est égal à : "+resultat12);
confirm("le produit de (b+a)(b+a) est égal à : "+resultat13);
confirm("le produit de (a+b)/(a+b) est égal à : "+resultat14);